# Generated by Django 5.2.1 on 2025-09-23 20:12

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('materials', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamAnalysis',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subject', models.CharField(db_index=True, help_text='Subject being analyzed', max_length=100)),
                ('analysis_data', models.JSONField(default=dict, help_text='Analysis results including trends and predictions')),
                ('documents_analyzed', models.ManyToManyField(related_name='analyses', to='materials.examdocument')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_analyses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Exam Analysis',
                'verbose_name_plural': 'Exam Analyses',
                'ordering': ['-created_at'],
            },
        ),
    ]
