# Generated by Django 5.2.1 on 2025-09-28 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ExamAnalysis',
        ),
    ]
