# Generated by Django 5.2.1 on 2025-09-23 20:12

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('profile_picture', models.ImageField(blank=True, help_text='Upload your profile picture (JPG, PNG, GIF up to 5MB)', null=True, upload_to='profile_pictures/')),
                ('bio', models.TextField(blank=True, help_text='Tell us about yourself', max_length=500)),
                ('is_deleted', models.BooleanField(default=False, help_text='Soft-delete flag for manual admin use only')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
